include(FetchContent)
set(FETCHCONTENT_UPDATES_DISCONNECTED TRUE)
set(SUBMODULES_DIR "${PROJECT_SOURCE_DIR}/submodules")
set(EXTERNAL_DIR "${PROJECT_SOURCE_DIR}/external")

include(deps/OpenVolumeMesh)
include(deps/OpenMesh)
include(deps/glm)
include(deps/nlohmann_json)
include(deps/ToLoG)
include(deps/webgpu)
include(deps/imgui)
include(deps/ibex)
include(deps/rapidobj)
include(deps/iconfontcppheaders)
