include(FetchContent)
set(FETCHCONTENT_UPDATES_DISCONNECTED TRUE)
set(SUBMODULES_DIR "${PROJECT_SOURCE_DIR}/submodules")
set(EXTERNAL_DIR "${PROJECT_SOURCE_DIR}/external")

include("${PROJECT_SOURCE_DIR}/cmake/deps/OpenVolumeMesh.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/OpenMesh.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/glm.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/nlohmann_json.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/webgpu.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/ToLoG.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/imgui.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/ibex.cmake")
include("${PROJECT_SOURCE_DIR}/cmake/deps/iconfontcppheaders.cmake")
